Repository DeveloperAcademy-POSTECH/MacC-Team-Samsamhada, pull requests merged in 2022-11, with the labels that each got.

#88 [Design] 시공상황뷰(WorkinghistoryView) 레이아웃 1차 추가
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/WorkingHistoryView/UIComponent/WorkingHistoryViewContentCell.swift
  Samsam/ViewController/WorkingHistoryView/UIComponent/WorkingHistoryViewContentHeader.swift
  Samsam/ViewController/WorkingHistoryView/UIComponent/WorkingHistoryViewTopCell.swift
  Samsam/ViewController/WorkingHistoryView/UIComponent/WorkingHistoryViewTopHeader.swift
  Samsam/ViewController/WorkingHistoryView/WorkingHistoryViewController.swift
Labels: design

#93 [Feature] 시공작성 화면 이미지 업로드 뷰 기능 수정 및 추가
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/PostingImageButtonCell.swift
  Samsam/ViewController/PostingImageViewController.swift
  Samsam/ViewController/PostingWritingView.swift
Labels: feature

#98 [Feature] Metro UI구현
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/HistoryView/WorkingHistoryView/UIComponent/BezierCurveConfiguration.swift
  Samsam/ViewController/HistoryView/WorkingHistoryView/UIComponent/MetroViewController.swift
  Samsam/ViewController/HistoryView/WorkingHistoryView/UIComponent/WorkingHistoryViewTopHeader.swift
Labels: feature

#102 [Feature] 카테고리 코어 데이터 받아오기 / 이미지 코어 데이터 업로드 / 코어 데이터 관련 기타 버그 수정
  Samsam/CoreData/CoreDataManager.swift
  Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
  Samsam/ViewController/HistoryView/WorkingHistoryView/WorkingHistoryViewController.swift
  Samsam/ViewController/PostingCategoryViewController.swift
  Samsam/ViewController/PostingImageViewController.swift
  Samsam/ViewController/PostingWritingView.swift
  Samsam/ViewController/RoomCategoryViewController.swift
Labels: feature

#104 [Feature] 담당자연락처입력뷰(PhoneNumView) 자동 하이픈(-) 생성 및 번호길이 제한
  Samsam/Global/Extension/PhoneNumberStyle+.swift
  Samsam/ViewController/PhoneNumViewController.swift
Labels: feature

#107 [Feature] 칩뷰 디자인 및 기능 만들기 / 이미지 불러오기 버그 수정
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/ChipViewController.swift
  Samsam/ViewController/DetailView/ImageDetailViewController.swift
  Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
  Samsam/ViewController/HistoryView/WorkingHistoryView/WorkingHistoryViewController.swift
  Samsam/ViewController/PostingView/CategoryCell.swift
  Samsam/ViewController/PostingView/PostingCategoryViewController.swift
  Samsam/ViewController/PostingView/PostingImageButtonCell.swift
  Samsam/ViewController/PostingView/PostingImageCell.swift
  Samsam/ViewController/PostingView/PostingImageViewController.swift
  Samsam/ViewController/PostingView/PostingWritingView.swift
  Samsam/ViewController/RoomCreationView/RoomCategoryViewController.swift
  Samsam/ViewController/RoomCreationView/RoomCodeViewController.swift
Labels: design, feature

#111 [Feature] 방생성뷰(RoomCreationView) 달력 아코디언 및 셀 커스텀
  Samsam.xcodeproj/project.pbxproj
  Samsam/Assets.xcassets/ColorAsset/buttonGray.colorset/Contents.json
  Samsam/Global/Extension/UIColor+.swift
  Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
  Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateFirstCell.swift
  Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateHeader.swift
  Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateSecondCell.swift
  Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewWarrantyCell.swift
Labels: feature

#118 [Feature] DetailView에서 ImageDetailView로 화면전환 및 ImageDetailView ScrollView로 수정
  Samsam/ViewController/DetailView/DetailViewController.swift
  Samsam/ViewController/DetailView/ImageDetailViewController.swift
Labels: feature

#127 [Feature] 방 생성에 필요한 정보 바인딩 및 초대코드 뷰 연결
  Network/Models/Request/StatusDTO.swift
  Samsam/ViewController/RoomCreationView/RoomCategoryViewController.swift
  Samsam/ViewController/RoomCreationView/RoomCodeViewController.swift
  Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
  Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewWarrantyCell.swift
  Samsam/ViewController/RoomListViewController.swift
Labels: feature

#132 [Feature] 전화번호뷰(PhoneNumView) 붙여넣기 기능 차단
  Samsam/ViewController/PhoneNumViewController.swift
Labels: feature

#134 [Feature] 시공상황작성뷰(PostingCategoryView) 데이터 연결
  Network/API/RoomAPI.swift
  Network/EndPoint/RoomEndPoint.swift
  Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
  Samsam/ViewController/PostingView/PostingCategoryViewController.swift
  Samsam/ViewController/PostingView/PostingImageViewController.swift
Labels: feature

#137 [Feature] 시공상황작성뷰(PostingImageView) 이미지 용량 대폭 감소
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
  Samsam/ViewController/PostingView/PostingImageCell.swift
  Samsam/ViewController/PostingView/PostingImageViewController.swift
Labels: feature

#140 [Feature] 시공상황작성뷰(PostingWritingView)에서 카테고리, 이미지, 텍스트 Post 작업
  Network/API/RoomAPI.swift
  Network/EndPoint/RoomEndPoint.swift
  Network/Models/Post.swift
  Network/Models/Request/PhotoDTO.swift
  Network/Models/Request/PostDTO.swift
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/ChipViewController.swift
  Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
  Samsam/ViewController/HistoryView/WorkingHistoryView/WorkingHistoryViewController.swift
  Samsam/ViewController/PostingView/PostingCategoryViewController.swift
  Samsam/ViewController/PostingView/PostingImageViewController.swift
  Samsam/ViewController/PostingView/PostingWritingView.swift
Labels: feature
