Repository DeveloperAcademy-POSTECH/MacC-Team-Samsamhada, pull requests merged in 2022-10, with the labels that each got.

#8 [Feature] AutoLayout 익스텐션 추가
  Samsam.xcodeproj/project.pbxproj
  Samsam/Global/Extension/AutoLayout+.swift
  Samsam/Global/Extension/aaa+.swift
  Samsam/ViewController/RoomListViewController.swift
Labels: feature

#11 [Design] 시공상황 뷰(WorkingHistoryView) UI 작업내용
  Samsam.xcodeproj/project.pbxproj
  Samsam/Assets.xcassets/TestImage.imageset/Contents.json
  Samsam/Assets.xcassets/TestImage.imageset/TestImage.jpeg
  Samsam/ViewController/WorkingHistoryView/UIComponent/WorkingHistoryViewCell.swift
  Samsam/ViewController/WorkingHistoryView/UIComponent/WorkingHistoryViewHeader.swift
  Samsam/ViewController/WorkingHistoryView/WorkingHistoryViewController.swift
Labels: design

#12 [Design] 방 목록 뷰 레이아웃 그리기
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/RoomListCell.swift
  Samsam/ViewController/RoomListViewController.swift
Labels: design

#25 [Design] 담당자 연락처 입력 뷰 레이아웃 수정
  Samsam/ViewController/PhoneNumViewController.swift
Labels: design

#28 [Design] 세부내용 뷰(DetailView) Layout 추가
  Samsam.xcodeproj/project.pbxproj
  Samsam/Assets.xcassets/Test01.imageset/Contents.json
  Samsam/Assets.xcassets/Test01.imageset/Test01.png
  Samsam/Assets.xcassets/Test02.imageset/Contents.json
  Samsam/Assets.xcassets/Test02.imageset/Test02.png
  Samsam/Assets.xcassets/Test03.imageset/Contents.json
  Samsam/Assets.xcassets/Test03.imageset/Test03.png
  Samsam/Assets.xcassets/Test04.imageset/Contents.json
  Samsam/Assets.xcassets/Test04.imageset/Test04.png
  Samsam/ViewController/DetailView/DetailViewController.swift
Labels: design

#37 [Feature] 세부사항 뷰(DetailView) 수정버튼 클릭 시 네비게이션 이동
  Samsam/ViewController/DetailView/DetailViewController.swift
Labels: feature

#38 [Feature] 시공내역뷰(workingHistoryView) 풀스크린 모달 추가, 변수명 수정
  Samsam/ViewController/WorkingHistoryView/WorkingHistoryViewController.swift
Labels: feature

#24 [Design] 시공상황 작성 카테코리뷰 레이아웃 그리기
  Samsam.xcodeproj/project.pbxproj
  Samsam/Assets.xcassets/category1.imageset/Contents.json
  Samsam/Assets.xcassets/category1.imageset/category.png
  Samsam/Assets.xcassets/category2.imageset/Contents.json
  Samsam/Assets.xcassets/category2.imageset/Group 17.png
  Samsam/Base.lproj/Main.storyboard
  Samsam/ViewController/CategoryCell.swift
  Samsam/ViewController/PostingCategoryViewController.swift
  Samsam/ViewController/PostingImageViewController.swift
Labels: design

#41 [Feature] 세부사항 뷰(DetailView) 공유기능 추가
  Samsam.xcodeproj/project.pbxproj
  Samsam/Info.plist
  Samsam/ViewController/DetailView/DetailViewController.swift
Labels: feature

#46 [Design] 방 생성 뷰(RoomCreationView) 레이아웃
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
Labels: design

#50 [Feature] 방생성뷰 FullScreen Dismiss 기능 추가
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/RoomCreationCell.swift
  Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
  Samsam/ViewController/RoomListViewController.swift
Labels: feature

#51 [Feature] 방 목록 뷰에서 네비게이션 이동
  Samsam/ViewController/RoomListCell.swift
  Samsam/ViewController/RoomListViewController.swift
  Samsam/ViewController/WorkingHistoryView/WorkingHistoryViewController.swift
Labels: feature

#31 [Design] 시공상황 작성 텍스트 뷰 Layout 생성
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/PostingWritingView.swift
Labels: design

#45 [Design] 방 생성 카테코리 뷰 Layout 생성
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/RoomCategoryViewController.swift
  Samsam/ViewController/RoomCodeViewController.swift
Labels: design

#52 [Feature] CoreData 추가
  Samsam.xcodeproj/project.pbxproj
  Samsam/CoreData/CategoryEntity+CoreDataClass.swift
  Samsam/CoreData/CategoryEntity+CoreDataProperties.swift
  Samsam/CoreData/CoreDataManager.swift
  Samsam/CoreData/DataTable.xcdatamodeld/DataTable.xcdatamodel/contents
  Samsam/CoreData/PhotoEntity+CoreDataClass.swift
  Samsam/CoreData/PhotoEntity+CoreDataProperties.swift
  Samsam/CoreData/PostingEntity+CoreDataClass.swift
  Samsam/CoreData/PostingEntity+CoreDataProperties.swift
  Samsam/CoreData/RoomEntity+CoreDataClass.swift
  Samsam/CoreData/RoomEntity+CoreDataProperties.swift
  Samsam/CoreData/WorkingStatusEntity+CoreDataClass.swift
  Samsam/CoreData/WorkingStatusEntity+CoreDataProperties.swift
  Samsam/Global/AppDelegate.swift
Labels: feature

#53 [Feat] 시공내역 뷰(WorkHistoryView) 네비게이션 기능 추가, 컨텐츠 타입 추가
  Samsam/ViewController/WorkingHistoryView/UIComponent/WorkingHistoryViewCell.swift
  Samsam/ViewController/WorkingHistoryView/WorkingHistoryViewController.swift
Labels: feature

#58 [Feature] 번호 입력 시 확인버튼 Disable/Enable 상태 변화
  Samsam.xcodeproj/project.pbxproj
  Samsam/Global/Extension/hideKeyboard+.swift
  Samsam/ViewController/PhoneNumViewController.swift
  Samsam/ViewController/PostingWritingView.swift
  Samsam/ViewController/WorkingHistoryView/WorkingHistoryViewController.swift
Labels: feature

#66 [Design] 세부 이미지뷰(ImageDetailView) UI
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/DetailView/DetailViewController.swift
  Samsam/ViewController/ImageDetailViewController.swift
Labels: design

#67 [Feature] 시공상황 작성 뷰, 풀스크린모달 및 네비게이션컨트롤 구현
  Samsam/ViewController/WorkingHistoryView/WorkingHistoryViewController.swift
Labels: feature

#68 [Feature] 사진 핀치, 드래그를 이용한 제스처 활용
  Samsam/ViewController/ImageDetailViewController.swift
Labels: feature

#75 [Feature] 방 생성 정보 저장 및 방목록 뷰에서 불러오기
  Samsam/ViewController/PostingCategoryViewController.swift
  Samsam/ViewController/RoomCategoryViewController.swift
  Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
  Samsam/ViewController/RoomListCell.swift
  Samsam/ViewController/RoomListViewController.swift
Labels: feature

#74 [Feature] 시공작성 화면 뷰 네비게이션바 Backbutton 만들기
  Samsam/ViewController/PostingCategoryViewController.swift
  Samsam/ViewController/PostingImageViewController.swift
  Samsam/ViewController/PostingWritingView.swift
Labels: feature

#63 [Design] 방생성 완료 뷰 Layout 생성 및 기능 구현
  Samsam/ViewController/RoomCodeViewController.swift
Labels: design, feature

#82 [Feature] 시공작성 화면 뷰 이미지 코어 데이터 연결
  Samsam/ViewController/PostingImageViewController.swift
  Samsam/ViewController/PostingWritingView.swift
Labels: feature

#81 [Design] Color extension 추가 및 Color Lofi색상으로 통일
  Samsam.xcodeproj/project.pbxproj
  Samsam/Assets.xcassets/ColorAsset/Contents.json
  Samsam/Assets.xcassets/ColorAsset/bloodRed.colorset/Contents.json
  Samsam/Assets.xcassets/ColorAsset/campanulaBlue.colorset/Contents.json
  Samsam/Assets.xcassets/ColorAsset/campanulaPink.colorset/Contents.json
  Samsam/Assets.xcassets/ColorAsset/mainBlack.colorset/Contents.json
  Samsam/Assets.xcassets/ColorAsset/selectedGray.colorset/Contents.json
  Samsam/Assets.xcassets/ColorAsset/unSelectedGray.colorset/Contents.json
  Samsam/Global/Extension/UIColor+.swift
  Samsam/ViewController/DetailView/DetailViewController.swift
  Samsam/ViewController/PostingCategoryViewController.swift
  Samsam/ViewController/PostingImageViewController.swift
  Samsam/ViewController/PostingWritingView.swift
  Samsam/ViewController/RoomCategoryViewController.swift
  Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
  Samsam/ViewController/RoomListCell.swift
  Samsam/ViewController/WorkingHistoryView/UIComponent/WorkingHistoryViewCell.swift
  Samsam/ViewController/WorkingHistoryView/WorkingHistoryViewController.swift
Labels: design

#84 [Feature] 코어 데이터 연결 마무리
  Samsam/ViewController/DetailView/DetailViewController.swift
  Samsam/ViewController/PostingCategoryViewController.swift
  Samsam/ViewController/PostingImageViewController.swift
  Samsam/ViewController/PostingWritingView.swift
  Samsam/ViewController/WorkingHistoryView/UIComponent/WorkingHistoryViewCell.swift
  Samsam/ViewController/WorkingHistoryView/WorkingHistoryViewController.swift
Labels: feature
