Repository DeveloperAcademy-POSTECH/MacC-Team-Samsamhada, pull requests merged in 2022-12, with the labels that each got.

#143 [Feature] 세부시공상태뷰(Detailview) 이미지 및 텍스트 데이터 바인딩 및 공유 기능
  Samsam/Global/SceneDelegate.swift
  Samsam/ViewController/ChipViewController.swift
  Samsam/ViewController/DetailView/DetailViewController.swift
  Samsam/ViewController/HistoryView/WorkingHistoryView/WorkingHistoryViewController.swift
Labels: feature

#144 [Feature] 설정 뷰 만들기 / 방 정보 수정 기능 구현
  Network/API/RoomAPI.swift
  Network/API/WorkerAPI.swift
  Network/EndPoint/RoomEndPoint.swift
  Network/EndPoint/WorkerEndPoint.swift
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
  Samsam/ViewController/RoomCreationView/RoomCategoryViewController.swift
  Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
  Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewWarrantyCell.swift
  Samsam/ViewController/RoomListViewController.swift
  Samsam/ViewController/SettingView/DeveloperViewController.swift
  Samsam/ViewController/SettingView/SettingRoomViewController.swift
  Samsam/ViewController/SettingView/SettingWorkerViewController.swift
  Samsam/ViewController/SettingView/VersionViewController.swift
Labels: design, feature

#145 [Feature] 세부이미지뷰(imageDetailView) 이미지 바인딩 및 스타일 변경
  Samsam/Assets.xcassets/TestImage.imageset/Contents.json
  Samsam/Assets.xcassets/TestImage.imageset/TestImage.jpeg
  Samsam/ViewController/DetailView/DetailViewController.swift
  Samsam/ViewController/DetailView/ImageDetailViewController.swift
Labels: feature

#148 [Feature] 카테고리별시공상황(ChipView)로 데이터 바인딩
  Samsam/ViewController/ChipViewController.swift
  Samsam/ViewController/HistoryView/WorkingHistoryView/WorkingHistoryViewController.swift
  Samsam/ViewController/PostingView/PostingCategoryViewController.swift
  Samsam/ViewController/RoomListViewController.swift
Labels: feature

#151 [Feature] 업자 개인 정보 수정 기능 구현
  Network/API/WorkerAPI.swift
  Network/EndPoint/WorkerEndPoint.swift
  Network/Models/Request/WorkerDTO.swift
  Samsam.xcodeproj/project.pbxproj
  Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
  Samsam/ViewController/SettingView/SettingWorkerViewController.swift
Labels: design, feature

#155 [Fix] 텍스트 입력 시, 키보드와 함께 버튼 올라가고 내려가기
  Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
Labels: feature, fix

#157 [Design] 카테고리 이름 변경
  Samsam/CoreData/CoreDataManager.swift
Labels: design

#156 [Design] 칩뷰 하단 세이프에리어 삭제
  Samsam/ViewController/ChipViewController.swift
Labels: design

#158 [Feature] 애플 로그인 기능 추가
  Network/EndPoint/LoginEndPoint.swift
  Network/Models/Request/LoginDTO.swift
  Samsam.xcodeproj/project.pbxproj
  Samsam/Assets.xcassets/ColorAsset/giwazipBlue.colorset/Contents.json
  Samsam/Global/AppDelegate.swift
  Samsam/Global/Extension/UIColor+.swift
  Samsam/Global/SceneDelegate.swift
  Samsam/ViewController/LoginViewController.swift
  Samsam/ViewController/PhoneNumViewController.swift
  Samsam/ViewController/RoomListViewController.swift
Labels: feature

#159 [Design] 문의내역뷰(InquiryView) 생성, HistoryView들에 문구 추가
  Samsam/ViewController/DetailView/DetailViewController.swift
  Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
  Samsam/ViewController/HistoryView/WorkingHistoryView/UIComponent/WorkingHistoryViewContentCell.swift
  Samsam/ViewController/HistoryView/WorkingHistoryView/WorkingHistoryViewController.swift
Labels: design

#165 [Design] HistoryView들 게시글 수정
  Samsam/ViewController/HistoryView/WorkingHistoryView/UIComponent/WorkingHistoryViewContentCell.swift
  Samsam/ViewController/HistoryView/WorkingHistoryView/WorkingHistoryViewController.swift
Labels: design, fix

#168 [Design] DetailView의 이미지 납작해지는 문제 수정
  Samsam/ViewController/DetailView/DetailViewController.swift
Labels: design

#171 [Design] 새로운 디자인에 맞게 게시물 상세 페이지 수정
  Samsam/ViewController/DetailView/DetailViewController.swift
Labels: design

#180 [Feature] 회원 탈퇴 및 로그아웃 기능 추가
  Samsam/ViewController/LoginViewController.swift
  Samsam/ViewController/PhoneNumViewController.swift
  Samsam/ViewController/SettingView/SettingWorkerViewController.swift
Labels: feature

#181 [Resource] 카테고리뷰에 사용할 이미지 에셋 추가
  Samsam/Assets.xcassets/CategoryImage/Bathroom.imageset/Bathroom.png
  Samsam/Assets.xcassets/CategoryImage/Bathroom.imageset/Contents.json
  Samsam/Assets.xcassets/CategoryImage/BigRoom.imageset/BigRoom.png
  Samsam/Assets.xcassets/CategoryImage/BigRoom.imageset/Contents.json
  Samsam/Assets.xcassets/CategoryImage/Contents.json
  Samsam/Assets.xcassets/CategoryImage/ETC.imageset/Contents.json
  Samsam/Assets.xcassets/CategoryImage/ETC.imageset/ETC.png
  Samsam/Assets.xcassets/CategoryImage/HomeEntrance.imageset/Contents.json
  Samsam/Assets.xcassets/CategoryImage/HomeEntrance.imageset/HomeEntrance.png
  Samsam/Assets.xcassets/CategoryImage/Kitchen.imageset/Contents.json
  Samsam/Assets.xcassets/CategoryImage/Kitchen.imageset/Kitchen.png
  Samsam/Assets.xcassets/CategoryImage/LivingRoom.imageset/Contents.json
  Samsam/Assets.xcassets/CategoryImage/LivingRoom.imageset/LivingRoom.png
  Samsam/Assets.xcassets/CategoryImage/MasterBedroom.imageset/Contents.json
  Samsam/Assets.xcassets/CategoryImage/MasterBedroom.imageset/MasterBedroom.png
  Samsam/Assets.xcassets/CategoryImage/Plan.imageset/Contents.json
  Samsam/Assets.xcassets/CategoryImage/Plan.imageset/Plan.png
  Samsam/Assets.xcassets/CategoryImage/SmallRoom.imageset/Contents.json
  Samsam/Assets.xcassets/CategoryImage/SmallRoom.imageset/SmallRoom.png
  Samsam/Assets.xcassets/CategoryImage/UtilityRoom.imageset/Contents.json
  Samsam/Assets.xcassets/CategoryImage/UtilityRoom.imageset/UtilityRoom.png
  Samsam/Assets.xcassets/CategoryImage/Veranda.imageset/Contents.json
  Samsam/Assets.xcassets/CategoryImage/Veranda.imageset/Veranda.png
  Samsam/ViewController/PostingView/CategoryCell.swift
Labels: resource

#161 [Design] 백그라운드 및 버튼 색상 변경
  Samsam/Assets.xcassets/ColorAsset/backgroundGray.colorset/Contents.json
  Samsam/Global/Extension/UIColor+.swift
  Samsam/ViewController/ChipViewController.swift
  Samsam/ViewController/DetailView/DetailViewController.swift
  Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
  Samsam/ViewController/HistoryView/WorkingHistoryView/WorkingHistoryViewController.swift
  Samsam/ViewController/PhoneNumViewController.swift
  Samsam/ViewController/PostingView/PostingCategoryViewController.swift
  Samsam/ViewController/PostingView/PostingImageViewController.swift
  Samsam/ViewController/PostingView/PostingWritingView.swift
  Samsam/ViewController/RoomCreationView/RoomCategoryViewController.swift
  Samsam/ViewController/RoomCreationView/RoomCodeViewController.swift
  Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
  Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateFirstCell.swift
  Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateSecondCell.swift
  Samsam/ViewController/RoomListViewController.swift
  Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
  Samsam/ViewController/SettingView/SettingRoomViewController.swift
  Samsam/ViewController/SettingView/SettingWorkerViewController.swift
Labels: design

#185 [Design] 개발자 정보 뷰 수정 / 버전 정보 네이게이션 클릭 비활성화
  Samsam/Assets.xcassets/Dinner.imageset/Contents.json
  Samsam/Assets.xcassets/Dinner.imageset/Dinner.png
  Samsam/Assets.xcassets/Eddy.imageset/Contents.json
  Samsam/Assets.xcassets/Eddy.imageset/Eddy.png
  Samsam/Assets.xcassets/Meenu.imageset/Contents.json
  Samsam/Assets.xcassets/Meenu.imageset/Meenu.png
  Samsam/ViewController/SettingView/DeveloperViewController.swift
  Samsam/ViewController/SettingView/SettingWorkerViewController.swift
Labels: design

#191 [!HOTFIX] 회원가입시 전화번호를 입력하지 않고 어플리케이션을 종료하면 후에 수정이 불가능한 버그 수정
  Samsam/Global/SceneDelegate.swift
  Samsam/ViewController/PhoneNumViewController.swift
  Samsam/ViewController/SettingView/SettingWorkerViewController.swift
Labels: !HOTFIX

#188 [Design] 시공상황 작성 뷰 디자인 변경 / 시공상황 수정 기능 구현 / 셀 백그라운드 버그 해결
  Network/API/RoomAPI.swift
  Network/EndPoint/RoomEndPoint.swift
  Network/Models/Request/PostDTO.swift
  Samsam/ViewController/DetailView/DetailViewController.swift
  Samsam/ViewController/HistoryView/WorkingHistoryView/WorkingHistoryViewController.swift
  Samsam/ViewController/PostingView/PostingImageViewController.swift
  Samsam/ViewController/PostingView/PostingWritingView.swift
  Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateFirstCell.swift
  Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateHeader.swift
  Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateSecondCell.swift
  Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewWarrantyCell.swift
Labels: bug, design, feature

#190 [Design] 카테고리뷰 디자인 수정 및 애니메이션 추가, Coredata 코드 삭제, 버튼 디자인 수정
  Samsam.xcodeproj/project.pbxproj
  Samsam/CoreData/Category.swift
  Samsam/CoreData/CategoryEntity+CoreDataClass.swift
  Samsam/CoreData/CategoryEntity+CoreDataProperties.swift
  Samsam/CoreData/CoreDataManager.swift
  Samsam/CoreData/PhotoEntity+CoreDataClass.swift
  Samsam/CoreData/PhotoEntity+CoreDataProperties.swift
  Samsam/CoreData/PostingEntity+CoreDataClass.swift
  Samsam/CoreData/PostingEntity+CoreDataProperties.swift
  Samsam/CoreData/RoomEntity+CoreDataClass.swift
  Samsam/CoreData/RoomEntity+CoreDataProperties.swift
  Samsam/CoreData/WorkingStatusEntity+CoreDataClass.swift
  Samsam/CoreData/WorkingStatusEntity+CoreDataProperties.swift
  Samsam/Global/Category.swift
  Samsam/Global/Extension/Gradient+.swift
  Samsam/ViewController/ChipViewController.swift
  Samsam/ViewController/DetailView/DetailViewController.swift
  Samsam/ViewController/HistoryView/InquiryHistoryView/InquiryHistoryViewController.swift
  Samsam/ViewController/HistoryView/WorkingHistoryView/WorkingHistoryViewController.swift
  Samsam/ViewController/PhoneNumViewController.swift
  Samsam/ViewController/PostingView/CategoryCell.swift
  Samsam/ViewController/PostingView/PostingCategoryViewController.swift
  Samsam/ViewController/PostingView/PostingImageViewController.swift
  Samsam/ViewController/PostingView/PostingWritingView.swift
  Samsam/ViewController/RoomCreationView/RoomCategoryViewController.swift
  Samsam/ViewController/RoomCreationView/RoomCodeViewController.swift
  Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
  Samsam/ViewController/RoomListView/RoomListViewController.swift
  Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
  Samsam/ViewController/ViewController.swift
Labels: design, feature, fix

#193 [!HOTFIX] 버튼 중복 터치 해결
  Samsam/ViewController/PostingView/PostingImageViewController.swift
  Samsam/ViewController/PostingView/PostingWritingView.swift
  Samsam/ViewController/RoomCreationView/RoomCategoryViewController.swift
  Samsam/ViewController/RoomListView/RoomListViewController.swift
Labels: !HOTFIX
